package Models.Pojo;
// Generated 19-may-2021 10:48:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Guerra generated by hbm2java
 */
@Entity
@Table(name="guerra"
    ,catalog="guerras_bd"
)
public class Guerra  implements java.io.Serializable {


     private Integer idGuerra;
     private String anioInicio;
     private String anioFin;
     private String nombre;
     private Set contendientes = new HashSet(0);

    public Guerra() {
    }

	
    public Guerra(String anioInicio, String nombre) {
        this.anioInicio = anioInicio;
        this.nombre = nombre;
    }
    public Guerra(String anioInicio, String anioFin, String nombre, Set contendientes) {
       this.anioInicio = anioInicio;
       this.anioFin = anioFin;
       this.nombre = nombre;
       this.contendientes = contendientes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_guerra", unique=true, nullable=false)
    public Integer getIdGuerra() {
        return this.idGuerra;
    }
    
    public void setIdGuerra(Integer idGuerra) {
        this.idGuerra = idGuerra;
    }

    
    @Column(name="anio_inicio", nullable=false, length=15)
    public String getAnioInicio() {
        return this.anioInicio;
    }
    
    public void setAnioInicio(String anioInicio) {
        this.anioInicio = anioInicio;
    }

    
    @Column(name="anio_fin", length=15)
    public String getAnioFin() {
        return this.anioFin;
    }
    
    public void setAnioFin(String anioFin) {
        this.anioFin = anioFin;
    }

    
    @Column(name="nombre", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="guerra")
    public Set getContendientes() {
        return this.contendientes;
    }
    
    public void setContendientes(Set contendientes) {
        this.contendientes = contendientes;
    }

    @Override
    public String toString() {
	return "Guerra{" + "idGuerra=" + idGuerra + ", anioInicio=" + anioInicio + ", anioFin=" + anioFin + ", nombre=" + nombre + ", contendientes=" + contendientes + '}';
    }

    



}


