package Models.Pojo;
// Generated 19-may-2021 10:48:07 by Hibernate Tools 4.3.1


import javax.persistence.*;
import static javax.persistence.GenerationType.IDENTITY;


/**
 * UnionBandos generated by hbm2java
 */
@Entity
@Table(name="union_bandos"
    ,catalog="guerras_bd"
    , uniqueConstraints = @UniqueConstraint(columnNames={"id_pais", "id_contendiente"}) 
)
public class UnionBandos  implements java.io.Serializable {


     private Integer idUnionBandos;
     private Contendiente contendiente;
     private Pais pais;
     private String fechaUnion;
     private String fechaAbandono;

    public UnionBandos() {
    }

	
    public UnionBandos(Contendiente contendiente, Pais pais) {
        this.contendiente = contendiente;
        this.pais = pais;
    }
    public UnionBandos(Contendiente contendiente, Pais pais, String fechaUnion, String fechaAbandono) {
       this.contendiente = contendiente;
       this.pais = pais;
       this.fechaUnion = fechaUnion;
       this.fechaAbandono = fechaAbandono;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_union_bandos", unique=true, nullable=false)
    public Integer getIdUnionBandos() {
        return this.idUnionBandos;
    }
    
    public void setIdUnionBandos(Integer idUnionBandos) {
        this.idUnionBandos = idUnionBandos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_contendiente", nullable=false)
    public Contendiente getContendiente() {
        return this.contendiente;
    }
    
    public void setContendiente(Contendiente contendiente) {
        this.contendiente = contendiente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_pais", nullable=false)
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }

    
    @Column(name="fecha_union", length=10)
    public String getFechaUnion() {
        return this.fechaUnion;
    }
    
    public void setFechaUnion(String fechaUnion) {
        this.fechaUnion = fechaUnion;
    }

    
    @Column(name="fecha_abandono", length=10)
    public String getFechaAbandono() {
        return this.fechaAbandono;
    }
    
    public void setFechaAbandono(String fechaAbandono) {
        this.fechaAbandono = fechaAbandono;
    }




}


