/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author grupo1
 */
public class viewWars extends JDialog {

    /**
     * Creates new form warView
     *
     * @param parent
     * @param modal
     */
    
      imagenPanel fondo = new imagenPanel();
    public viewWars(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

             this.setContentPane(fondo);
        initComponents();
        setWindow();

    }

    public JButton getAdd_button() {
        return add_button;
    }

    public JButton getDelete_button() {
        return delete_button;
    }

    public JButton getEdit_button() {
        return edit_button;
    }

//    public JTextField getEnd_date_text() {
//        return end_date_text1;
//    }

    public JButton getExit_button() {
        return exit_button;
    }

    public JTextField getId_text() {
        return id_text;
    }

    public JTable getJtableWars() {
        return jtableWars;
    }

    public JTextField getName_text() {
        return name_text;
    }

//    public JTextField getStart_date_text() {
//        return start_date_text1;
//    }

    public JTextField getTxtfFilterSearch() {
        return txtfFilterSearch;
    }

    public JDateChooser getEnd_date_text() {
	return end_date_text;
    }

    public JDateChooser getStart_date_text() {
	return start_date_text;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFilterSearch = new javax.swing.JLabel();
        txtfFilterSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableWars = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        name_text = new javax.swing.JTextField();
        name_label = new javax.swing.JLabel();
        start_date_label = new javax.swing.JLabel();
        id_text = new javax.swing.JTextField();
        id_label = new javax.swing.JLabel();
        start_date_text = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        add_button = new javax.swing.JButton();
        edit_button = new javax.swing.JButton();
        exit_button = new javax.swing.JButton();
        delete_button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        end_date_text = new com.toedter.calendar.JDateChooser();
        end_date_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblFilterSearch.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFilterSearch.setForeground(new java.awt.Color(204, 204, 204));
        lblFilterSearch.setText("Busqueda");

        jtableWars.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtableWars);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(name_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 139, 222, 28));

        name_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        name_label.setForeground(new java.awt.Color(204, 204, 204));
        name_label.setText("Nombre de la Guerra");
        jPanel1.add(name_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 107, -1, -1));

        start_date_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        start_date_label.setForeground(new java.awt.Color(204, 204, 204));
        start_date_label.setText("Fecha de inicio");
        jPanel1.add(start_date_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 179, 129, -1));
        jPanel1.add(id_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 67, 222, 28));

        id_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        id_label.setForeground(new java.awt.Color(204, 204, 204));
        id_label.setText("ID Guerra");
        jPanel1.add(id_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 35, 129, -1));

        start_date_text.setDateFormatString("dd-MM-yyyy");
        start_date_text.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        start_date_text.setMaxSelectableDate(new java.util.Date(1625097703000L));
        jPanel1.add(start_date_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 170, 30));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add_button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add_button.setText("Añadir");
        add_button.setPreferredSize(new java.awt.Dimension(120, 62));
        jPanel2.add(add_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 18, 171, 75));

        edit_button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edit_button.setText("Editar");
        edit_button.setPreferredSize(new java.awt.Dimension(120, 62));
        jPanel2.add(edit_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 18, 168, 75));

        exit_button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        exit_button.setText("Salir");
        exit_button.setPreferredSize(new java.awt.Dimension(120, 62));
        jPanel2.add(exit_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 123, 168, 72));

        delete_button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        delete_button.setText("Eliminar");
        delete_button.setPreferredSize(new java.awt.Dimension(120, 62));
        jPanel2.add(delete_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 123, 171, 72));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/guerras.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 220, 170));

        end_date_text.setDateFormatString("dd-MM-yyyy");

        end_date_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        end_date_label.setForeground(new java.awt.Color(204, 204, 204));
        end_date_label.setText("Fecha de fin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFilterSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtfFilterSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(end_date_label, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(end_date_text, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(38, 38, 38)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfFilterSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFilterSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(end_date_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(end_date_text, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_button;
    private javax.swing.JButton delete_button;
    private javax.swing.JButton edit_button;
    private javax.swing.JLabel end_date_label;
    private com.toedter.calendar.JDateChooser end_date_text;
    private javax.swing.JButton exit_button;
    private javax.swing.JLabel id_label;
    private javax.swing.JTextField id_text;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtableWars;
    private javax.swing.JLabel lblFilterSearch;
    private javax.swing.JLabel name_label;
    private javax.swing.JTextField name_text;
    private javax.swing.JLabel start_date_label;
    private com.toedter.calendar.JDateChooser start_date_text;
    private javax.swing.JTextField txtfFilterSearch;
    // End of variables declaration//GEN-END:variables

    private void setWindow() {
        setTitle("GUERRAS");
        setLocationRelativeTo(this);
    }

}
